import { Hospital, Patient, ResearchStudy, DataAccessEvent, DatasetMetadata } from './types';

export const mockHospitals: Hospital[] = [
  {
    id: 'h1',
    name: 'Johns Hopkins Medical',
    patientsCount: 12840,
    genomicSamplesCount: 12840,
    researchProjects: 8,
    privacyBudgetUsed: 0.42,
    privacyBudgetTotal: 1.0,
  },
  {
    id: 'h2',
    name: 'Mayo Clinic Research',
    patientsCount: 9320,
    genomicSamplesCount: 9320,
    researchProjects: 6,
    privacyBudgetUsed: 0.31,
    privacyBudgetTotal: 1.0,
  },
  {
    id: 'h3',
    name: 'Stanford Med Center',
    patientsCount: 15200,
    genomicSamplesCount: 15200,
    researchProjects: 11,
    privacyBudgetUsed: 0.58,
    privacyBudgetTotal: 1.0,
  },
  {
    id: 'h4',
    name: 'MGH Harvard Affiliate',
    patientsCount: 18900,
    genomicSamplesCount: 18900,
    researchProjects: 14,
    privacyBudgetUsed: 0.19,
    privacyBudgetTotal: 1.0,
  }
];

export const mockDataAccessEvents: DataAccessEvent[] = [
  {
    id: 'da1',
    studyId: 'rs1',
    studyName: 'BRCA1/2 Variant Effects on Treatment Outcomes',
    accessDate: '2026-03-25',
    dataUsed: ['Genomic Variants', 'Clinical Outcomes'],
    purpose: 'Differential privacy query — ε=0.05 consumed for variant frequency analysis',
  },
  {
    id: 'da2',
    studyId: 'rs2',
    studyName: 'Polygenic Risk Score for Cardiac Events',
    accessDate: '2026-03-25',
    dataUsed: ['Genomic Variants', 'Family History'],
    purpose: 'Research Discovery Agent matched institutions for cardiac risk study',
  },
  {
    id: 'da3',
    studyId: 'rs3',
    studyName: 'Rare Neurodegenerative Genomic Biomarkers',
    accessDate: '2026-03-25',
    dataUsed: ['Genomic Variants', 'Diagnostic Records'],
    purpose: 'Neurodegenerative model training completed - AUC improved to 0.87',
  },
];

export const mockPatient: Patient = {
  id: 'p1',
  anonymizedId: 'PAT-7F8A9B2C',
  dataTypes: ['Genomic Variants', 'Clinical Outcomes', 'Family History', 'Diagnostic Records'],
  consentedProjects: ['rs1', 'rs2', 'rs3'],
  dataAccessLog: mockDataAccessEvents,
};

export const mockStudies: ResearchStudy[] = [
  {
    id: 'rs1',
    title: 'BRCA1/2 Variant Effects on Treatment Outcomes',
    researcher: 'Dr. Sarah Chen',
    institution: 'Johns Hopkins Medical',
    description: 'Multi-institutional federated analysis investigating BRCA1, BRCA2, PALB2, and RAD51C variant effects on oncology treatment responses.',
    dataRequirements: ['Genomic Variants (BRCA1/2)', 'Clinical Outcomes', 'Family History'],
    status: 'active',
    partnersFound: 2,
    participatingHospitals: ['h1', 'h3'],
    privacyLevel: 'high',
    statisticalPower: 0.94,
    createdAt: '2025-11-01',
  },
  {
    id: 'rs2',
    title: 'Polygenic Risk Score for Cardiac Events',
    researcher: 'Dr. Marcus Webb',
    institution: 'MGH Harvard Affiliate',
    description: 'Partner discovery phase for risk stratification using APOE, LDLR, PCSK9, and MYH7 variants to predict cardiac events.',
    dataRequirements: ['Genomic Variants', 'Cardiac Imaging', 'Demographics', 'Lab Results'],
    status: 'discovering',
    partnersFound: 2,
    participatingHospitals: ['h2', 'h4'],
    privacyLevel: 'high',
    statisticalPower: 0.90,
    createdAt: '2026-01-15',
  },
  {
    id: 'rs3',
    title: 'Rare Neurodegenerative Genomic Biomarkers',
    researcher: 'Dr. Priya Nair',
    institution: 'Mayo Clinic Research',
    description: 'Biomarker discovery focusing on APP, PSEN1, PSEN2, MAPT, and SNCA genes across federated datasets.',
    dataRequirements: ['Genomic Variants', 'Neurological Diagnostics', 'Clinical Notes'],
    status: 'completed',
    partnersFound: 2,
    participatingHospitals: ['h2', 'h3'],
    privacyLevel: 'high',
    statisticalPower: 0.97,
    results: 'Identified 8 significant findings with an improved AUC of 0.87 for neurodegenerative model training.',
    createdAt: '2025-08-01',
  },
  {
    id: 'rs4',
    title: 'Pharmacogenomic Markers in Oncology',
    researcher: 'Dr. James Liu',
    institution: 'Johns Hopkins Medical',
    description: 'Drug response prediction utilizing DPYD, UGT1A1, TPMT, and CYP2D6 genomic variants.',
    dataRequirements: ['Genomic Variants', 'Medication Records', 'Clinical Outcomes'],
    status: 'active',
    partnersFound: 1,
    participatingHospitals: ['h1'],
    privacyLevel: 'high',
    statisticalPower: 0.91,
    createdAt: '2025-12-01',
  },
];

export const mockDatasetMetadata: DatasetMetadata[] = [
  {
    hospitalId: 'h1',
    hospitalName: 'Johns Hopkins Medical',
    dataTypes: ['Whole Exome Sequencing', 'Targeted Cancer Panels', 'Pharmacogenomics', 'Clinical Outcomes'],
    sampleSize: 12840,
    demographicDiversity: 0.87,
    qualityScore: 0.94,
    availableForStudy: true,
  },
  {
    hospitalId: 'h2',
    hospitalName: 'Mayo Clinic Research',
    dataTypes: ['Whole Genome Sequencing', 'RNA-Seq', 'Methylation Arrays', 'Neurology Records'],
    sampleSize: 9320,
    demographicDiversity: 0.82,
    qualityScore: 0.89,
    availableForStudy: true,
  },
  {
    hospitalId: 'h3',
    hospitalName: 'Stanford Med Center',
    dataTypes: ['Single Cell Genomics', 'CRISPR Screens', 'Spatial Transcriptomics', 'Oncology Records'],
    sampleSize: 15200,
    demographicDiversity: 0.79,
    qualityScore: 0.92,
    availableForStudy: true,
  },
  {
    hospitalId: 'h4',
    hospitalName: 'MGH Harvard Affiliate',
    dataTypes: ['Long Read Sequencing', 'Proteogenomics', 'Metagenomics', 'Cardiology Records'],
    sampleSize: 18900,
    demographicDiversity: 0.91,
    qualityScore: 0.88,
    availableForStudy: true,
  }
];
